# Generated by Django 2.1.5 on 2019-10-17 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191017_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealorder', to='api.Meal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealorder', to='api.Order')),
            ],
        ),
        migrations.RemoveField(
            model_name='meal_order',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='meal_order',
            name='order',
        ),
        migrations.DeleteModel(
            name='Meal_Order',
        ),
    ]
