# Generated by Django 2.1.5 on 2019-10-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
        ('api', '0003_auto_20191017_1540'),
    ]

    operations = [
    ]
