# Generated by Django 2.1.5 on 2019-10-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191020_1022'),
        ('api', '0004_merge_20191020_0921'),
    ]

    operations = [
    ]
