# Generated by Django 2.1.5 on 2019-10-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191020_1258'),
        ('api', '0006_merge_20191020_1136'),
    ]

    operations = [
    ]
